[project]
id = "ffzntdpojhlpzgcwoqlk"
name = "Ministerio360"
api_url = "https://ffzntdpojhlpzgcwoqlk.supabase.co"

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
